name: Run comment-annotator (.ts only)

on:
  push:

jobs:
  annotate:
    name: Annotate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: joonashak/comment-annotator@main
        with:
          include: "*.ts"
